export const GET_MAIN_SLIDER = "GET_ALLFILMS"; 
export const GET_MAIN_FILTER = "GET_MAIN_FILTER";
export const GET_MAIN_FILTER_CATEGORY_CURRENT = "GET_MAIN_FILTER_CATEGORY_CURRENT";
export const GET_MAIN_SLIDER_RANDOM = "GET_MAIN_SLIDER_RANDOM";

export const GET_FILM_DETAIL = "GET_FILM_DETAIL";

