export const GET_MAIN_SLIDER = "GET_MAIN_SLIDER"; 
export const GET_CATEGORIES = "GET_CATEGORIES";
export const GET_MAIN_FILTER_CATEGORY_CURRENT = "GET_MAIN_FILTER_CATEGORY_CURRENT";
export const GET_MAIN_SLIDER_RANDOM = "GET_MAIN_SLIDER_RANDOM";
export const GET_FILM_DETAIL = "GET_FILM_DETAIL";

